import React from 'react'
import PropTypes from 'prop-types'
import Feed from './Feed';

const FeedContainer = ({ feeds }) => {

  return (
    <div className="container">
		  {feeds.map(feed => (
				<Feed key={feed.id} {...feed} />
        //<Todo key={todo.id} {...todo} onClick={() => toggleTodo(todo.id)} />
      ))}
    </div>
  )
}

FeedContainer.propTypes = {
  feeds: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number.isRequired, //can be fixed to string
      title: PropTypes.string.isRequired,
			userName: PropTypes.string.isRequired,
			date: PropTypes.string.isRequired,
			text: PropTypes.string.isRequired,
    }).isRequired
  ).isRequired
}
// https://reactjs.org/docs/typechecking-with-proptypes.html

export default FeedContainer


/*
■Container Components
Purpose        : How things work (data fetching, state updates)
Aware of Redux : Yes
To read data   : Subscribe to Redux state
To change data : Dispatch Redux actions
Are written    : Usually generated by React Redux

- data comes from store
- dispatch action to change data
- Wrap
*/
